import Head from 'next/head'
import Link from "next/link"
import { useState } from 'react'
import { useEffect } from 'react'
import styles from '../src/styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>TBookMap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        TODO: home
      </>
    </div>
  )
}
