import Head from 'next/head'
import Link from "next/link"
import { Btn } from '../src/components/atoms/Button'
import { Header } from '../src/components/organisms/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>TBookMap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  )
}
