import { Box, Heading, Image } from '@chakra-ui/react'
import Head from 'next/head'
import Link from "next/link"
import { BookAll } from '../src/components/organisms/BookAll'
import { Footer } from '../src/components/organisms/Footer'
import { Header } from '../src/components/organisms/Header'
import Kv from '../src/components/organisms/Kv'

export default function Home(props: any) {
  const { article } = props
  console.table(article)
  return (
    <div>
      <Head>
        <title>TBookMap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Box p={{base: 8, md:16}} d="flex" flexDirection="column" alignItems="center" maxW="765px" w="100%" margin="0 auto">
        <Kv />
        <BookAll />
      </Box>
      <Footer />
    </div >
  )
}

export const getServerSideProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts")
  const article = await res.json()
  return {
    props: {
      article
    }
  }
}
